apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: product-catalog-backend:v1
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: productdb
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
